/**
 * Lemoji mapping — maps emoji shortcodes and common text emoticons
 * to lemoji image paths from the python-discord/branding set.
 */

export const LEMOJI_MAP: Record<string, string> = {
	// Shortcode → lemoji filename (without extension)
	":smile:": "lemon_smile",
	":happy:": "lemon_happy",
	":blush:": "lemon_blush",
	":wink:": "lemon_wink",
	":smirk:": "lemon_smirk",
	":smug:": "lemon_smug",
	":pleased:": "lemon_pleased",
	":hearteyes:": "lemon_hearteyes",
	":starstruck:": "lemon_starstruck",
	":hyperpleased:": "lemon_hyperpleased",
	":tongue:": "lemon_tongue",
	":xd:": "lemon_xd",
	":thinking:": "lemon_thinking",
	":raised_eyebrow:": "lemon_raised_eyebrow",
	":pensive:": "lemon_pensive",
	":sleepy:": "lemon_sleepy",
	":yawn:": "lemon_yawn",
	":grimace:": "lemon_grimace",
	":unamused:": "lemon_unamused",
	":grumpy:": "lemon_grumpy",
	":angrysad:": "lemon_angrysad",
	":enraged:": "lemon_enraged",
	":scared:": "lemon_scared",
	":surprised:": "lemon_surprised",
	":exploding_head:": "lemon_exploding_head",
	":sweat:": "lemon_sweat",
	":mask:": "lemon_mask",
	":holding_back_tears:": "lemon_holding_back_tears",
	":sentimental:": "lemon_sentimental",
	":zipped_mouth:": "lemon_zipped_mouth",
	":fingerguns:": "lemon_fingerguns",
	":sunglasses:": "lemon_fingerguns_shades",
	":swag:": "lemon_swag",
	":glass:": "lemon_glass",
	":eyes:": "lemon_eyes",
	":ping:": "lemon_ping",
	":pika:": "lemon_pika",
	":cyclops:": "lemon_cyclops",
	":long:": "lemon_long",
	":halloween:": "lemon_halloween",
	":warpaint:": "lemon_warpaint",
	":partying:": "lemoji_partying",
	":pleading:": "lemoji_pleading",
	// Text emoticon aliases
	":)": "lemon_smile",
	":D": "lemon_happy",
	";)": "lemon_wink",
	":(": "lemon_pensive",
	":P": "lemon_tongue",
	":O": "lemon_surprised",
	xD: "lemon_xd",
	XD: "lemon_xd",
	":/": "lemon_grimace",
	"B)": "lemon_fingerguns_shades",
};

/** All available lemoji filenames (for decorative use). */
export const ALL_LEMOJIS = [
	"lemon_angrysad",
	"lemon_blush",
	"lemon_cyclops",
	"lemon_enraged",
	"lemon_exploding_head",
	"lemon_eyes",
	"lemon_fingerguns",
	"lemon_fingerguns_shades",
	"lemon_glass",
	"lemon_grimace",
	"lemon_grumpy",
	"lemon_halloween",
	"lemon_happy",
	"lemon_hearteyes",
	"lemon_holding_back_tears",
	"lemon_hyperpleased",
	"lemon_long",
	"lemon_mask",
	"lemon_pensive",
	"lemon_pika",
	"lemon_ping",
	"lemon_pleased",
	"lemon_raised_eyebrow",
	"lemon_scared",
	"lemon_sentimental",
	"lemon_sleepy",
	"lemon_smile",
	"lemon_smirk",
	"lemon_smug",
	"lemon_starstruck",
	"lemon_surprised",
	"lemon_swag",
	"lemon_sweat",
	"lemon_thinking",
	"lemon_tongue",
	"lemon_unamused",
	"lemon_warpaint",
	"lemon_wink",
	"lemon_xd",
	"lemon_yawn",
	"lemon_zipped_mouth",
	"lemoji_partying",
	"lemoji_pleading",
] as const;

/** A curated subset of "positive vibes" lemojis for decorative scattering. */
export const DECORATIVE_LEMOJIS = [
	"lemon_happy",
	"lemon_smile",
	"lemon_pleased",
	"lemon_wink",
	"lemon_fingerguns",
	"lemon_starstruck",
	"lemon_hyperpleased",
	"lemon_swag",
	"lemoji_partying",
	"lemon_blush",
] as const;

export function lemojiPath(name: string): string {
	return `/images/lemoji/${name}.avif`;
}
