// Procedural fortune cookie generator (mad-libs style)

const ADJECTIVES = [
	"UNEXPECTED",
	"ANCIENT",
	"MAGNIFICENT",
	"SUSPICIOUS",
	"ENORMOUS",
	"HUMBLE",
	"FORBIDDEN",
	"CURIOUS",
	"UNSPEAKABLE",
	"GENTLE",
	"RECKLESS",
	"PROFOUND",
	"MEDIOCRE",
	"INEVITABLE",
	"DAMP",
	"LUMINOUS",
	"FURIOUS",
	"QUESTIONABLE",
	"ASTONISHING",
	"MODEST",
	"RELUCTANT",
	"PECULIAR",
	"TREMENDOUS",
	"HAUNTED",
	"ADEQUATE",
	"INVISIBLE",
	"LEGENDARY",
	"CHAOTIC",
	"PROSPEROUS",
	"UNREMARKABLE",
	"BEWILDERING",
	"VOLCANIC",
	"TENDER",
	"ABSURD",
	"COURAGEOUS",
	"SQUEAKY",
	"INFINITE",
	"IMPROBABLE",
	"BLESSED",
	"FERAL",
];

const NOUNS = [
	"OPPORTUNITY",
	"SANDWICH",
	"STRANGER",
	"WINDFALL",
	"DUCK",
	"MIRACLE",
	"POTATO",
	"ADVENTURE",
	"FORTUNE",
	"SUITCASE",
	"REVELATION",
	"BICYCLE",
	"CATASTROPHE",
	"BLESSING",
	"GOAT",
	"WEASEL",
	"HARMONY",
	"ENVELOPE",
	"SHIPWRECK",
	"TROMBONE",
	"DESTINY",
	"PUDDING",
	"ALLIANCE",
	"CALAMITY",
	"SHOVEL",
	"PROPHECY",
	"TURNIP",
	"SPECTACLE",
	"INHERITANCE",
	"BADGER",
	"WHEELBARROW",
	"EPIPHANY",
	"SAUSAGE",
	"CONTINENT",
	"DREAM",
	"CABBAGE",
	"LIGHTHOUSE",
	"BETRAYAL",
	"HAMMOCK",
	"PINEAPPLE",
];

const NOUNS_PLURAL = [
	"OPPORTUNITIES",
	"SANDWICHES",
	"STRANGERS",
	"BLESSINGS",
	"DUCKS",
	"MIRACLES",
	"POTATOES",
	"ADVENTURES",
	"FORTUNES",
	"SUITCASES",
	"REVELATIONS",
	"BICYCLES",
	"CHANGES",
	"WATERS",
	"GOATS",
	"WEASELS",
	"ENVELOPES",
	"SHIPWRECKS",
	"TROMBONES",
	"PUDDINGS",
	"ALLIANCES",
	"SHOVELS",
	"PROPHECIES",
	"TURNIPS",
	"BADGERS",
	"WHEELBARROWS",
	"SAUSAGES",
	"CONTINENTS",
	"DREAMS",
	"CABBAGES",
	"LIGHTHOUSES",
	"BETRAYALS",
	"HAMMOCKS",
	"PINEAPPLES",
	"EVENTS",
];

const VERBS = [
	"LOVE",
	"FEAR",
	"SEEK",
	"ADMIRE",
	"AVOID",
	"DEVOUR",
	"QUESTION",
	"CHERISH",
	"CONFRONT",
	"SUMMON",
	"IGNORE",
	"WORSHIP",
	"JUGGLE",
	"BETRAY",
	"UNLEASH",
	"EMBRACE",
	"SHOPLIFT",
	"CARESS",
	"LAUNCH",
	"RENAME",
];

const VERBS_FUTURE = [
	"FIND",
	"RECEIVE",
	"WITNESS",
	"DISCOVER",
	"ENCOUNTER",
	"INHERIT",
	"SURVIVE",
	"MISPLACE",
	"BEFRIEND",
	"ACCIDENTALLY DESTROY",
	"NARROWLY AVOID",
	"BE HAUNTED BY",
	"COLLIDE WITH",
	"STUMBLE UPON",
	"OUTLIVE",
];

const ADVERBS = [
	"SOON",
	"UNEXPECTEDLY",
	"QUIETLY",
	"VIOLENTLY",
	"HAPPILY",
	"RELUCTANTLY",
	"SPECTACULARLY",
	"GRADUALLY",
	"SUSPICIOUSLY",
	"MAGNIFICENTLY",
	"INEVITABLY",
	"CLUMSILY",
	"FURIOUSLY",
	"TENDERLY",
	"SIDEWAYS",
];

const PLACES = [
	"IN YOUR HOME",
	"IN A DREAM",
	"BEHIND A DOOR",
	"ACROSS THE GREAT WATERS",
	"NEAR A VOLCANO",
	"IN A PARKING LOT",
	"UNDER YOUR BED",
	"AT THE POST OFFICE",
	"IN A SWAMP",
	"ON A MOUNTAIN",
	"IN THE PRODUCE AISLE",
	"ABOARD A SHIP",
];

function pick<T>(arr: T[]): T {
	return arr[Math.floor(Math.random() * arr.length)]!;
}

/** Returns "A WORD" or "AN WORD" based on whether word starts with a vowel sound. */
function aan(word: string): string {
	return "AEIOU".includes(word[0]!) ? `AN ${word}` : `A ${word}`;
}

const TEMPLATES = [
	() => `${aan(pick(ADJECTIVES))} ${pick(NOUNS)} IS IN STORE FOR YOU ${pick(ADVERBS)}.`,
	() => `YOU WILL ALWAYS BE SURROUNDED BY ${pick(ADJECTIVES)} ${pick(NOUNS_PLURAL)}.`,
	() => `${aan(pick(ADJECTIVES))} ${pick(NOUNS)} LIES AHEAD OF YOU.`,
	() => `YOU WILL ${pick(VERBS_FUTURE)} ${aan(pick(ADJECTIVES))} ${pick(NOUNS)} ${pick(ADVERBS)}.`,
	() =>
		`${aan(pick(ADJECTIVES))} ${pick(NOUNS)} WILL TURN INTO ${aan(pick(ADJECTIVES))} ${pick(NOUNS)}.`,
	() => `YOUR ${pick(ADJECTIVES)} ${pick(NOUNS)} IS ABOUT TO PAY OFF.`,
	() => `THE ONE YOU ${pick(VERBS)} IS CLOSER THAN YOU THINK.`,
	() => `${pick(ADJECTIVES)} ${pick(NOUNS_PLURAL)} WILL TAKE PLACE SHORTLY IN YOUR ${pick(NOUNS)}.`,
	() => `SOMEONE FROM YOUR PAST WILL ${pick(ADVERBS)} ${pick(VERBS_FUTURE)} YOUR ${pick(NOUNS)}.`,
	() => `${aan(pick(ADJECTIVES))} ${pick(NOUNS)} WILL ${pick(ADVERBS)} BE YOURS.`,
	() => `YOU WILL FIND YOUR ${pick(NOUNS)} WHERE YOU LEAST EXPECT IT.`,
	() => {
		const a = pick(ADJECTIVES),
			b = pick(ADJECTIVES),
			c = pick(ADJECTIVES);
		return `${aan(a)}, ${b}, AND ${c} ${pick(NOUNS)} WILL BE COMING INTO YOUR LIFE.`;
	},
	() => `THE ${pick(NOUNS)} OF ${pick(NOUNS)} IS SHINING ON YOU.`,
	() => `A SMALL ACT OF ${pick(NOUNS)} WILL GO A LONG WAY.`,
	() =>
		`${aan(pick(ADJECTIVES))} ${pick(NOUNS)} WILL BRING YOU ${pick(ADJECTIVES)} ${pick(NOUNS_PLURAL)}.`,
	() => `YOU WILL ${pick(ADVERBS)} ${pick(VERBS_FUTURE)} ${aan(pick(NOUNS))} ${pick(PLACES)}.`,
	() =>
		`MANY ${pick(ADJECTIVES)} AND ${pick(ADJECTIVES)} ${pick(NOUNS_PLURAL)} ARE IN STORE FOR YOU.`,
	() => `YOUR ${pick(NOUNS_PLURAL)} WILL PROVE TO BE ESPECIALLY ${pick(ADJECTIVES)} THIS WEEK.`,
	() => `A NEW ${pick(NOUNS)} IS ABOUT TO ${pick(VERBS)} EVERYTHING YOU KNOW.`,
	() => `YOUR ${pick(NOUNS)} WILL BE ${pick(ADJECTIVES)} AND ${pick(ADJECTIVES)}.`,
	() => `THE NEAR FUTURE HOLDS ${aan(pick(NOUNS))} OF ${pick(ADJECTIVES)} ${pick(NOUNS)}.`,
	() => `BEWARE THE ${pick(ADJECTIVES)} ${pick(NOUNS)}. IT ${pick(ADVERBS)} ${pick(VERBS)}S BACK.`,
	() => `YOU WILL MAKE MANY ${pick(NOUNS_PLURAL)} BEFORE SETTLING ${pick(ADVERBS)}.`,
	() => `${pick(NOUNS)} IS THE ROOT OF ALL ${pick(NOUNS)}. EMBRACE IT ${pick(ADVERBS)}.`,
	() =>
		`HE WHO ${pick(VERBS)}S ${aan(pick(NOUNS))} ${pick(ADVERBS)} SHALL NEVER ${pick(VERBS)} ALONE.`,
];

export function generateFortune(): string {
	return pick(TEMPLATES)();
}
